# Versión de AppVeyor
version: 1.6.{build}

# Imagen del entorno de construcción (Windows)
image: Visual Studio 2019

# Variables de entorno
environment:
  PHP_URL: 'https://windows.php.net/downloads/releases/php-8.2.12-Win32-vs16-x64.zip'

# Instalación de PHP y Composer
install:
  # Descargar PHP
  - ps: |
      $ErrorActionPreference = 'Stop'
      $phpPath = "C:\\php"
      if (-Not (Test-Path $phpPath)) {
        New-Item -ItemType Directory -Path $phpPath
      }
      $webClient = New-Object System.Net.WebClient
      $webClient.DownloadFile($env:PHP_URL, "$phpPath\\php.zip")
      Expand-Archive -Path "$phpPath\\php.zip" -DestinationPath $phpPath
      $env:Path += ";$phpPath\\php-8.2.12-Win32-vs16-x64"
      Write-Host "PHP installed to $phpPath\\php-8.2.12-Win32-vs16-x64"
  
  # Descargar Composer
  - ps: |
      $composerUrl = 'https://getcomposer.org/installer'
      $composerSetup = "$phpPath\\composer-setup.php"
      $webClient.DownloadFile($composerUrl, $composerSetup)
      php $composerSetup --install-dir=$phpPath --filename=composer
      $env:Path += ";$phpPath"
      Write-Host "Composer installed to $phpPath"

# Instalar dependencias de PHP usando Composer
before_build:
  - cmd: composer install

# Construcción y verificación de sintaxis
build_script:
  - echo Build started
  - php -l src # Verifica que los archivos PHP no tienen errores de sintaxis

artifacts:
  - path: php.log
    name: PHP Log
