# Versi贸n de AppVeyor
version: 1.7.{build}

# Imagen del entorno de construcci贸n (Windows)
image: Visual Studio 2019

# Variables de entorno
environment:
  PHP_URL: 'https://windows.php.net/downloads/releases/php-8.2.12-Win32-vs16-x64.zip'

# Instalaci贸n de PHP y Composer
install:
  # Descargar y configurar PHP
  - ps: |
      $ErrorActionPreference = 'Stop'
      $phpPath = "C:\\php"
      if (-Not (Test-Path $phpPath)) {
        New-Item -ItemType Directory -Path $phpPath
      }
      $webClient = New-Object System.Net.WebClient
      $phpZipPath = "$phpPath\\php.zip"
      $webClient.DownloadFile($env:PHP_URL, $phpZipPath)
      Expand-Archive -Path $phpZipPath -DestinationPath $phpPath
      $phpFolder = Get-ChildItem -Path $phpPath | Where-Object { $_.PsIsContainer } | Select-Object -First 1
      $env:Path += ";$phpPath\\$phpFolder"
      Write-Host "PHP installed to $phpPath\\$phpFolder"
  
  # Descargar y configurar Composer
  - ps: |
      $composerUrl = 'https://getcomposer.org/installer'
      $composerSetup = "$phpPath\\composer-setup.php"
      $webClient.DownloadFile($composerUrl, $composerSetup)
      php $composerSetup --install-dir=$phpPath --filename=composer
      $env:Path += ";$phpPath"
      Write-Host "Composer installed to $phpPath"

# Instalar dependencias de PHP usando Composer
before_build:
  - ps: |
      & "$phpPath\\composer" install

# Verificaci贸n de sintaxis PHP
build_script:
  - ps: |
      Get-ChildItem -Recurse -Include *.php | ForEach-Object { php -l $_.FullName }

# Sin despliegue ni notificaciones
