# Versión de AppVeyor
version: 1.10.{build}

# Imagen del entorno de construcción (Windows)
image: Visual Studio 2019

# Variables de entorno
environment:
  PHP_URL: 'https://windows.php.net/downloads/releases/php-8.2.20-nts-Win32-vs16-x86.zip'
  PHP_DIR: 'C:\\php'
  PHP_ZIP: 'C:\\php\\php.zip'

# Instalación de PHP y Composer
install:
  # Descargar y configurar PHP
  - ps: |
      $ErrorActionPreference = 'Stop'
      $phpPath = $env:PHP_DIR
      $phpZip = $env:PHP_ZIP

      # Crear directorio para PHP
      if (-Not (Test-Path $phpPath)) {
        New-Item -ItemType Directory -Path $phpPath
      }

      # Descargar PHP
      Write-Host "Downloading PHP from $($env:PHP_URL)..."
      Invoke-WebRequest -Uri $env:PHP_URL -OutFile $phpZip

      # Verificar que el archivo ZIP no esté dañado
      Write-Host "Verifying downloaded ZIP file..."
      $zipTest = Test-Archive -Path $phpZip
      if (-Not $zipTest) {
        throw "The downloaded ZIP file is corrupted or incomplete."
      }

      # Expandir el archivo ZIP
      Write-Host "Extracting PHP files..."
      Expand-Archive -Path $phpZip -DestinationPath $phpPath -Force

      # Encontrar la carpeta de PHP y agregarla al PATH
      $phpFolder = Get-ChildItem -Path $phpPath | Where-Object { $_.PsIsContainer } | Select-Object -First 1
      $env:Path += ";$phpPath\\$phpFolder.Name"

      Write-Host "PHP installed to $($phpPath)\\$($phpFolder.Name)"
  
  # Descargar y configurar Composer
  - ps: |
      $composerUrl = 'https://getcomposer.org/installer'
      $composerSetup = "$phpPath\\composer-setup.php"
      Write-Host "Downloading Composer from $composerUrl..."
      Invoke-WebRequest -Uri $composerUrl -OutFile $composerSetup
      php $composerSetup --install-dir=$phpPath --filename=composer
      $env:Path += ";$phpPath"

      Write-Host "Composer installed to $phpPath"

# Instalar dependencias de PHP usando Composer
before_build:
  - ps: |
      & "$env:PHP_DIR\\composer" install

# Verificación de sintaxis PHP
build_script:
  - ps: |
      Get-ChildItem -Recurse -Include *.php | ForEach-Object { php -l $_.FullName }

# Sin despliegue ni notificaciones
