# Versi贸n de AppVeyor
version: 2.0.{build}

# Imagen del entorno de construcci贸n (Windows)
image: Visual Studio 2019

# Variables de entorno
environment:
  php_version: '8.1.12'

# Instalaci贸n de PHP y Composer
install:
  - ps: Install-Product php $env:php_version x64
  - ps: Install-Product composer

# Instalar dependencias de PHP usando Composer
before_build:
  - composer install

# Construcci贸n y pruebas
build_script:
  - echo Build started
  - php -l src # Verifica que los archivos PHP no tienen errores de sintaxis

