

image: Visual Studio 2019

environment:
  matrix:
    - PHP_VERSION: "8.2.12"

install:
  # Instalar Chocolatey
  - ps: |
      Set-ExecutionPolicy Bypass -Scope Process -Force; `
      iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))

  # Instalar PHP usando Chocolatey
  - choco install php --version $env:PHP_VERSION

build_script:
  - php -v
  # Agrega aquí los comandos necesarios para compilar y construir tu proyecto PHP

test_script:
  # Agrega aquí los comandos necesarios para ejecutar tus pruebas
